config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#new'

  resources :users
  resources :sessions
  resources :books

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image

  validates :title, :author_name, :isbn, :genre, :number_of_books, :published_year, presence: true
  validates :isbn, uniqueness: true
  validates :number_of_books, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate :published_year_cannot_be_in_the_future
  validate :image_presence_and_content_type

  private

  def published_year_cannot_be_in_the_future
    return if published_year.blank? || published_year.to_date <= Date.current

    errors.add(:published_year, "can't be in the future")
  end

  def image_presence_and_content_type
    if image.attached?
      unless image.content_type.in?(%w(image/jpeg image/png))
        errors.add(:image, 'must be a JPEG or PNG')
      end
    else
      errors.add(:image, 'must be attached')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :registerable,
         :recoverable, :rememberable, :validatable
  has_secure_password

  validates :user_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone_number, presence: true, format: { with: /\A\d{10}\z/, message: 'Please enter a valid number' }
  validates :password, presence: true, length: { minimum: 8 }
  validate :password_complexity

  enum user_role: { User: 0, Admin: 1 }

  private

  # def password_digest(password_digest)
  #   # You can add custom logic here before setting the password
  #   super
  # end

  def password_complexity
    return if password.blank? || password.match?(%r{\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#\$%^&*()_+{}\[\]:;<>,.?~\\\/-]).{8,}\z})

    errors.add(:password, 'must contain at least one uppercase letter, ' \
      'one lowercase letter, one special character, one number, ' \
      'and be at least 8 characters long')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    private

  def record_not_found
    render file: "#{Rails.root}/public/404.html", layout: false, status: 404
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]
  # before_action :set_book, only: [:show, :edit, :update, :destroy]
  # before_action :authorize_user!, only: [:edit, :update, :destroy]

  def index
    @books = Book.all.paginate(page: params[:page], per_page: 10)
    # @books = Book.all.page(params[:page]).per(10)
  end

  def show
    @book = Book.find_by(id: params[:id])
    return if @book.present?

    render json: { error: 'Book not found' }, status: 404
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = 'Book was successfully created.'
      redirect_to @book
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find_by(id: params[:id])
  end

  def update
    @book = Book.find_by(id: params[:id])

    if @book.update(book_params)
      flash[:success] = 'Book was successfully updated:)'
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find_by(id: params[:id])
    @book.destroy
    flash[:success] = 'Book was successfully destroyed.'
    redirect_to books_path
  end

  def search
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true).page(params[:page]).per(10)
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author_name, :isbn, :genre, :number_of_books, :published_year, :image)
  end

  def authorize_user!
    redirect_to root_path, alert: 'You are not authorized to perform this action.' unless current_user && current_user.admin?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
  render 'sessions/new'
end

  def create
      user = User.find_by(email: params[:session][:email].downcase)

        if user && user.authenticate(params[:session][:password])
          log_in user
          redirect_to user_path(user)
        else
          flash.now[:danger] = 'Invalid email/password combination'
          redirect_to root_url
        end
  rescue StandardError => e
    flash.now[:danger] = "An error occurred: #{e.message}"
    redirect_to root_url
  end
end

  def destroy
    log_out
    redirect_to root_url
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
    return if @user.present?

    render json: { error: 'User not found' }, status: 404
  end

  def index
    # @all_users = User.all
    @all_users = User.all.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'Welcome to JR Library Management :)'
      log_in @user
      redirect_to users_path
    else
      render :new
    end
  end

  def update
    @user = User.find_by(id: params[:id])

    if @user.update(user_params.merge(password: params[:user][:password]))
      flash[:notice] = 'Successfully Updated :)'
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to users_path
  end

  def home
    @books = Book.all
    @all_users = User.all.paginate(page: params[:page], per_page: 10)
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password, :first_name, :last_name, :email, :phone_number, :user_role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/views/books/_form.html.erb
    <%= form_with(model: book, local: true) do |f| %>
      <p>
        <%= f.label :Name %>
        <%= f.text_field :title, required: true %>
      </p>

      <p>
        <%= f.label :Author_name %>
        <%= f.text_field :author_name, required: true%>
      </p>

      <p>
        <%= f.label :ISBN %>
        <%= f.text_field :isbn, required: true %>
      </p>

      <p>
        <%= f.label :Total_books %>
        <%= f.text_field :number_of_books, required: true %>
      </p>

      <p>
        <%= f.label :Genre %>
        <%= f.text_field :genre, required: true %>
      </p>

      <p>
        <%= f.label :Published_Date %>
        <%= f.date_field :published_year, required: true %>
      </p>

      <p>
        <%= f.label :image %>
        <%= f.file_field :image, required: true%>
      </p>

      <p class="button-container">
          <%= f.submit 'Submit', class: 'submit-button' %>
          <%= link_to 'Back', books_path, class: 'button' %>
      </p>
   <% end %>

app/views/books/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Add Book</title>
  <%= stylesheet_link_tag 'common', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.4.2/zxcvbn.js"></script>
  <style>
    body {
        font-family: 'Philosopher', serif;
        background-color: #f4f4f4;
        color: #333;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        background: url('https://wallpaper-house.com/data/out/8/wallpaper2you_231925.jpg') center center fixed;
        background-size: cover;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Add Book</h1>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, 'Error') %> Please fix the following issues:</h2>
        <ul>
          <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= render 'form', book: @book %>
  </div>
</body>
</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>JRLibManagement</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'common', media: 'all', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>

<body>
  <div class="user-details">
    <div style="display: flex; justify-content: space-between; align-items: center; height: 2pc;">
      <h1>All Books</h1>
        <%= link_to new_book_path, class: 'button' do %>
          <i class="fas fa-plus icon"></i> Add
        <% end %>
    </div>
    <table>
      <thead>
        <tr>
          <th class="align_center">Image</th>
          <th>Title</th>
          <th>Genre</th>
          <th>View</th>
          <th>Remove</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book|%>
        <tr>
          <td style="text-align: center;"><%= image_tag book.image, style: 'height: 100px; width: auto;', loading: 'lazy' if book.image.present? %></td>
          <td><%= book.title%></td>
          <td><%= book.genre %></td>
          <td><%= link_to 'Show', book_path(book) %></td>
          <td><%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: "Are you sure on this Delete ?"} %></td>
        </tr>
        <%end%>
      </tbody>
    </table>

    <%= will_paginate @books %>

  </div>

  <%= yield %>
</body>

</html>

app/views/books/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Add Book</title>
  <%= stylesheet_link_tag 'common', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.4.2/zxcvbn.js"></script>
  <style>
    body {
        font-family: 'Philosopher', serif;
        background-color: #f4f4f4;
        color: #333;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        background: url('https://wallpaper-house.com/data/out/8/wallpaper2you_231925.jpg') center center fixed;
        background-size: cover;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Add Book</h1>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, 'Error') %> Please fix the following issues:</h2>
        <ul>
          <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= render 'form', book: @book %>
  </div>
</body>
</html>

app/views/books/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JRLibManagement</title>
      <%= stylesheet_link_tag 'common', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="style.css">

    <style>
        body, html {
            height: 100%;
            margin: 0;
            padding: 0;
            background: url('https://wallpaper-house.com/data/out/8/wallpaper2you_231925.jpg') center center fixed;
            background-size: cover;
            font-family: 'Montserrat', sans-serif;
        }

    </style>
</head>
<body>
    <div class="wrapper">
        <div class="user-card">
            <div class="user-card-img">
                <div class="initials"><%= image_tag @book.image, style: 'width: auto;', loading: 'lazy' if @book.image.present? %></div>
            </div>
            <div class="user-card-info">
                <div class="profile-header">
                    <h2>Book Detail</h2>
                    <% if current_user && current_user.admin? %>
                        <p class="edit-link">
                            <a href="<%= edit_book_path(@book) %>">
                                <i class="fas fa-edit"></i> Edit
                            </a>
                        </p>
                    <% end %>
                </div>
                <table>
                    <tr>
                        <th class="cofd">Author</th>
                        <td class="cofd"><%= @book.author_name %></td>
                    </tr>
                    <tr>
                        <th class="cofd">ISBN</th>
                        <td class="cofd"><%= @book.isbn %></td>
                    </tr>
                    <tr>
                        <th class="cofd">Genre</th>
                        <td class="cofd"><%= @book.genre %></td>
                    </tr>
                    <tr>
                        <th class="cofd" >Number of Books</th>
                        <td class="cofd"><%= @book.number_of_books %></td>
                    </tr>
                    <tr>
                        <th class="cofd">Published Date</th>
                        <td class="cofd"><%= @book.published_year %></td>
                    </tr>
                </table>
                                      <% if current_user && current_user.admin? %>
                        <tr>
                            <td colspan="2">
                                <%= link_to 'Back', books_path, class: 'btn-back' %>
                            </td>
                        </tr>
                    <% else %>
                        <tr>
                            <td colspan="2">
                                <%# <%= link_to 'Borrow', borrow_book_path(@book), class: 'btn-borrow' %> %>
                            </td>
                        </tr>
                    <% end %>
            </div>
        </div>
    </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JRLibManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JRLibManagement</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: 'Arial', sans-serif;
      background-color: #f4f4f4;
      color: #333;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100vh;
    }

header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: #aa8531;
  color: #fff;
  padding: 10px;
  text-align: center;
  width: 100%;
  position: fixed;
  top: 0;
  z-index: 1000;
}

    .logo {
      max-width: 30px;
    }

.search-bar {
  text-align: center;
  flex-grow: 1; /* Allow the search bar to grow and take available space */
}

    .search-input {
      padding: 8px;
      width: 300px;
      border: 1px solid #ddd;
      border-radius: 5px;
    }

    .search-button {
      padding: 8px 15px;
      background-color: #ddd;
      cursor: pointer;
      border: none;
      border-radius: 5px;
      margin-left: 10px;
    }

.cart-icon,
.profile-icon {
  max-width: 30px;
  margin-left: 10px;
  margin-right: 10px;
  cursor: pointer;
}

    main {
      text-align: center;
      padding: 70px 20px 20px; /* Adjust top padding to account for fixed header */
      width: 80%;
    }

    h1 {
      margin-top: 20px;
    }

    .button {
      display: block;
      margin: 20px auto;
      padding: 10px 20px;
      background-color: #007bff;
      color: #fff;
      text-align: center;
      text-decoration: none;
      border-radius: 5px;
      cursor: pointer;
    }

    .card-container {
      display: flex;
      justify-content: space-around;
      flex-wrap: wrap;
    }

    .card {
      width: 200px;
      padding: 15px;
      margin: 10px;
      background-color: #fff;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      border-radius: 5px;
    }

    /* Converted SCSS to CSS */
    figure {
      position: relative;
      display: flex;
      align-items: center;
      justify-content: center;
      width: 200px; /* Adjust the width as per your requirement */
      height: 300px; /* Adjust the height as per your requirement */
      border-radius: 10px;
      box-shadow: 
        0 1px 3px rgba(0,0,0,0.12), 
        0 1px 2px rgba(0,0,0,0.24);
      transition: all 0.3s cubic-bezier(.25,.8,.25,1);
      overflow: hidden;
      margin: 0 auto; /* Center the figure */
    }

    figure:hover {
      box-shadow: 
        0 14px 28px rgba(0,0,0,0.25), 
        0 10px 10px rgba(0,0,0,0.22);
    }

    figure:hover h1 {
      opacity: 0;
      transform: scale(0.7);
    }

    figure:hover img {
      transform: scale(1.25);
    }

    figure:hover figcaption {
      bottom: 0;
    }

    figure h1 {
      position: absolute;
      top: 10px;
      left: 10px;
      margin: 0;
      padding: 0;
      color: white;
      font-size: 24px; /* Adjust the font size as per your requirement */
      font-weight: 100;
      line-height: 1;
      opacity: 1;
      transform: scale(1);
      transition: 0.25s ease;
      z-index: 999;
    }

    figure img {
      height: 100%;
      width: 100%; /* Ensure the image takes the full width of the figure */
      transition: 0.25s;
    }

    figure figcaption {
      position: absolute;
      bottom: -34%;
      width: 100%;
      margin: 0;
      padding: 10px; /* Adjust padding as per your requirement */
      background-color: rgba(0, 0, 0, 0.85);
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.4);
      color: white;
      line-height: 1;
      transition: 0.25s;
    }

    figure figcaption h3 {
      margin: 0 0 10px; /* Adjust margin as per your requirement */
      padding: 0;
    }

    figure figcaption p {
      font-size: 12px; /* Adjust the font size as per your requirement */
      line-height: 1.5;
    }

    figure figcaption button {
      position: relative;
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 10px 0 0;
      padding: 8px 15px;
      background-color: #1abc9c;
      border: none;
      border-radius: 5px;
      color: white;
      font-size: 12px; /* Adjust the font size as per your requirement */
      cursor: pointer;
    }
  </style>
</head>
<body>

<header>
  <!-- Logo -->
  <%= link_to root_path do %>
    <%= image_tag('https://img.freepik.com/premium-vector/black-white-logo-letter-jr_773552-361.jpg', alt: 'Your Logo', class: 'logo') %>
  <% end %>
   <p>JRLibManagement</p>

  <!-- Search Bar -->
  <div class="search-bar">
    <%# <%= form_tag(search_users_path, method: :get) do %>
      <%# <%= text_field_tag :query, params[:query], placeholder: 'Search...', class: 'search-input' %>
      <%# <%= submit_tag 'Search', class: 'search-button' %>
    <%# <% end %>
  </div>

  <!-- Cart Image -->
  <%# <%= link_to cart_path do %>
    <%= image_tag('https://png.pngtree.com/png-vector/20190909/ourmid/pngtree-outline-bag-icon-symbol-isolated-png-image_1727847.jpg', alt: 'Shopping Cart', class: 'cart-icon') %>
  <%# <% end %>

  <!-- Profile Icon -->
  <%# <%= link_to profile_path do %>
    <%= image_tag('https://i.pinimg.com/originals/61/f7/5e/61f75ea9a680def2ed1c6929fe75aeee.jpg', alt: 'User Profile', class: 'profile-icon') %>
  <%# <% end %>
</header>

<main>
  <%# <%= link_to 'Back', users_path, class: 'button' %>
  <%# <%= link_to new_user_path, class: 'button' do %>
    <%# <i class="fas fa-plus icon"></i> Add
  <% end %>

  <div class="card-container">
    <% @books.each do |book| %>
      <figure class="image-block">
        <%= image_tag(book.image, alt: book.title) %>
        <figcaption>
          <%# <h3><%= book.author_name %></h3>
          <%# <p><%= book.title</p> %>
          <%= link_to 'Show', book_path(book), class: 'button' %>
        </figcaption>
      </figure>
    <% end %>
  </div>

</main>

</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>JRLibManagement</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>

  <style>
    body {
      font-family: 'Philosopher', serif;
      background-color: #f4f4f4;
      margin: 0;
      padding: 0;
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
      background: url('https://wallpaper-house.com/data/out/8/wallpaper2you_231925.jpg') center center fixed;
      background-size: cover;
    }

    .user-details {
      background-color: #fff;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
      margin-top: 20px;
      width: 62.5rem;
    }

    h1 {
      text-align: center;
      color: #aa8531;
      font-family: 'Philosopher',serif;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }

    th, td {
      border: 1px solid #ddd;
      padding: 8px;
      text-align: left;
    }

    thead {
      display: table-header-group;
      text-align: center;
    }

    th {
      background-color: #900c19;
      color: #f2c452;
    }

    a.button {
      display: inline-block;
      background-color: #900c19;
      color: #f2c452;
      padding: 10px 15px;
      text-align: center;
      text-decoration: none;
      margin-top: 20px;
      border-radius: 4px;
    }

    .icon {
      margin-right: 5px;
    }

    a.button:hover {
      background-color: #700215;
    }
  </style>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>

<body>
  <div class="user-details">
    <div style="display: flex; justify-content: space-between; align-items: center; height: 2pc;">
      <h1>All Users</h1>
        <%= link_to new_user_path, class: 'button' do %>
          <i class="fas fa-plus icon"></i> Add
        <% end %>
    </div>
    <table>
      <thead>
        <tr>
          <th>User Name</th>
          <th>User Role</th>
          <th>View</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @all_users.each do |user|%>
        <tr>
          <td><%= user.user_name %></td>
          <td><%= user.user_role %></td>
          <td><%= link_to 'Show', user_path(user) %></td>
          <td><%= link_to 'Edit', edit_user_path(user)%></td>
          <td><%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: "Are you sure on this Delete ?"} %></td>
        </tr>
        <%end%>
      </tbody>
    </table>

    <%= will_paginate @all_users %>

  </div>

  <%= yield %>
</body>

</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JRLibManagement</title>
      <%= stylesheet_link_tag 'common', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" href="style.css">

    <style>
        body, html {
            height: 100%;
            margin: 0;
            padding: 0;
            background: url('https://wallpaper-house.com/data/out/8/wallpaper2you_231925.jpg') center center fixed;
            background-size: cover;
            font-family: 'Montserrat', sans-serif;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="user-card">
            <div class="user-card-img">
                <div class="initials"><%= @user.first_name[0].upcase + @user.last_name[0].upcase %></div>
            </div>
            <div class="user-card-info">
                <div class="profile-header">
                    <h2>Profile</h2>
                    <p class="edit-link">
                        <a href="<%= edit_user_path(@user) %>">
                            <i class="fas fa-edit"></i>
                        </a>
                    </p>
                </div>
                <table>
                    <tr>
                        <th class="cofd">User Name</th>
                        <td class="cofd"><%= @user.user_name %></td>
                    </tr>
                    <tr>
                        <th class="cofd">First Name</th>
                        <td class="cofd"><%= @user.first_name %></td>
                    </tr>
                    <tr>
                        <th class="cofd">Last Name</th>
                        <td class="cofd"><%= @user.last_name %></td>
                    </tr>
                    <tr>
                        <th class="cofd">Email</th>
                        <td class="cofd"><%= @user.email %></td>
                    </tr>
                    <tr>
                        <th class="cofd">Phone</th>
                        <td class="cofd"><%= @user.user_name %></td>
                    </tr>
                    <tr>
                        <th class="cofd">User Role</th>
                        <td class="cofd"><%= @user.user_role %></td>
                    </tr>
                </table>
                    <%= link_to 'Back', users_path, class: 'btn-back' %>
            </div>
        </div>
    </div>
</body>
</html>